# Generated by Django 5.1.2 on 2024-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=36)),
                ('subject', models.CharField(max_length=36)),
                ('text', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
