# Generated by Django 5.1.2 on 2024-10-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teammodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammodel',
            old_name='title',
            new_name='name',
        ),
    ]
